#!/bin/bash

dir="$1"

for d in "$dir"/*; do
    if [[ -d "$d/.git" ]]; then
        (
            cd "$d" || exit 1;
            echo "Updating: $d"
            git fetch -apt
            revs="$(git rev-list --tags --max-count=1)"
            if [[ -z "$revs" ]]; then
                git pull
            else
                git checkout $(git describe --tags "$revs")
            fi
        )
    fi
done
